# Generated by Django 2.2.1 on 2019-08-31 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UploadMulti', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='processed_date',
            field=models.DateTimeField(null=True),
        ),
    ]
