# Generated by Django 2.2.1 on 2019-08-30 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UploadMulti', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='processed_by',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='uploaded_by',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
