# Generated by Django 2.2.1 on 2019-07-20 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UploadMulti', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='doc_id',
            field=models.ForeignKey(db_column='doc_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='UploadMulti.Document'),
        ),
    ]
