# Generated by Django 2.2.1 on 2019-08-11 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UploadMulti', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detail',
            name='Role_ref',
        ),
        migrations.AddField(
            model_name='detail',
            name='Role',
            field=models.ForeignKey(db_column='Role', null=True, on_delete=django.db.models.deletion.CASCADE, to='UploadMulti.Role'),
        ),
    ]
