# Generated by Django 2.2.1 on 2019-08-15 02:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UploadMulti', '0002_auto_20190811_1842'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detail',
            name='Role',
        ),
        migrations.AddField(
            model_name='detail',
            name='Role_ref',
            field=models.ForeignKey(db_column='Role_ref', null=True, on_delete=django.db.models.deletion.CASCADE, to='UploadMulti.Role'),
        ),
        migrations.AddField(
            model_name='detail',
            name='Roles',
            field=models.CharField(max_length=200, null=True, unique=True, verbose_name='Role_Name'),
        ),
    ]
