# Generated by Django 2.2.1 on 2019-08-30 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UploadMulti', '0002_auto_20190830_2004'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='processed_by',
            new_name='processed_at',
        ),
    ]
