# Generated by Django 2.2.1 on 2019-06-24 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UploadMulti', '0002_auto_20190523_1647'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Employee_Name', models.CharField(max_length=100, verbose_name='Employee Name')),
                ('Address_of_Employee', models.CharField(max_length=100, verbose_name='Address of Employee')),
                ('Company_Name', models.CharField(max_length=100, verbose_name='Company Name')),
                ('Address_of_Company', models.CharField(max_length=100, verbose_name='Address of Company')),
                ('Role', models.CharField(max_length=100, verbose_name='Role')),
                ('Base_Salary', models.CharField(max_length=100, verbose_name='Base Salary')),
                ('Date_of_Agreement', models.CharField(max_length=100, verbose_name='Date of Agreement')),
                ('Start_Date', models.CharField(max_length=100, verbose_name='Start Date')),
                ('End_Date', models.CharField(max_length=100, verbose_name='End Date')),
                ('Supervisor_Information', models.CharField(max_length=100, verbose_name='Supervisor Information')),
                ('Bonus', models.CharField(max_length=100, verbose_name='Bonus')),
                ('Notice_Period', models.CharField(max_length=100, verbose_name='Notice Period')),
                ('Other_Compensation', models.CharField(max_length=100, verbose_name='Other Compensation')),
                ('Non_Monetary_Benefits', models.CharField(max_length=100, verbose_name='Non Monetary Benefits')),
                ('Health_Insurance', models.CharField(max_length=100, verbose_name='Health Insurance')),
                ('_401k', models.CharField(max_length=100, verbose_name='401k')),
                ('At_will', models.CharField(max_length=100, verbose_name='At will')),
                ('Stock', models.CharField(max_length=100, verbose_name='Stock')),
                ('Vacation', models.CharField(max_length=100, verbose_name='Vacation')),
            ],
        ),
    ]
