# Generated by Django 2.2.1 on 2019-07-20 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UploadMulti', '0002_auto_20190720_1341'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detail',
            name='doc_id',
        ),
        migrations.AddField(
            model_name='detail',
            name='doc',
            field=models.ForeignKey(db_column='doc', null=True, on_delete=django.db.models.deletion.CASCADE, to='UploadMulti.Document'),
        ),
    ]
